name: .NET Build and Run   # Name of the workflow displayed in GitHub Actions UI

on:
  push:
    branches: [ main ]     # Triggers this workflow when pushing to 'main' branch
  pull_request:
    branches: [ main ]     # Also triggers this workflow on PRs to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu VM provided by GitHub runners

    steps:
    - name: Checkout code
      uses: actions/checkout@v3   # Step 1: Pull your code from the GitHub repository

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4   # Step 2: Install .NET SDK in the runner
      with:
        dotnet-version: '8.0.x'       # Specify .NET SDK version 8

    - name: Restore dependencies
      run: dotnet restore dotnetcicd/HelloWorldDotNet.csproj
      # Step 3: Restore NuGet packages from the actual path to .csproj

    - name: Build the app
      run: dotnet build dotnetcicd/HelloWorldDotNet.csproj --configuration Release
      # Step 4: Build using the correct .csproj path

    - name: Run the app
      run: dotnet run --project dotnetcicd/HelloWorldDotNet.csproj
      # Step 5: Run the app from the correct .csproj path
